### ISSUE TITLE
OS independent path separator

### ISSUE THREAD

**Issue by rbnscr** [HydrologyFrankfurt/ReWaterGAP#19]
Instead of using r"path_dir/filename" or any other variety, where the path separator / is hard coded, it would be nicer to use f"{path_dir}{**os.sep**}{filename}" as the separator might differ for different operating systems.

**Comment by nyenah** [comment]
Thank you so much for your feedback. Could you kindly direct me to the specific file name? Also, please note that all paths are managed within the code using the pathlib library.

**Comment by rbnscr** [comment]
Ah, I see. I went through some lines of code and prematurely thought to myself "I dont think this will work", but on further inspection I have to admit that I'm wrong 😅
