### ISSUE TITLE
Add contact information, team and project info to README.md

### ISSUE THREAD

**Issue by rreinecke** [HydrologyFrankfurt/ReWaterGAP#6]
Since the project is now public please add a short info to the README on:

- A remark that his is still under development
- Very short summary what this is about and that it is funded by the DFG
- A list of the team and their responsibilities (including link to github profiles)
- And a contact person and email for questions regarding the project

-> We haven't launched officially yet but someone might discover this project by accident so it would be good to have at least some info for people to follow up on :).

**Comment by Leon-Muehlenbruch** [comment]
I've written a first draft of a readme which can be found where the readme is located. In the first step I wanted to get all the important information down
- relevant links
- list of team members and their roles
- introduction to the project

Is there an official list of people that work on this that I can use for the readme?
Is there an official "spokesperson" and email people can contact?

Never wrote a readme before so I'll gladly take any suggestions!

**Comment by rreinecke** [comment]
Nice!
* Add Emmanuel's mail as main contact
* Use the links like [that](google.com) makes it a bit more readable

I think for a first version this is already really nice :). Maybe have a look at other big projects on Github and see how they design the readme. Something that you could then discuss with Emmanuel for an improved version later on.
